export type Product = {
  name: string;
  code: string;
  category: string;
  brand: string;
  link: string;
  price: number;
  image: string;
  slug: string;
  description: string;
  longDescription?: string;
  features?: string[];
  specifications?: { [key: string]: string };
};

export const allCollections: Product[] = [
  {
    name: "Royal Comfort Duvet",
    code: "duvet-royal",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/royal-comfort-duvet",
    price: 120.0,
    image: "/images/bedding/new/duvet_01.png",
    slug: "royal-comfort-duvet",
    description: "Experience the embrace of royalty with our premium velvet-touch duvet set.",
    longDescription:
      "Transform your bedroom into a palace with our Royal Comfort Duvet set. Crafted from crushed velvet top with a soft cotton underside, it offers the perfect balance of luxury and comfort.",
    features: [
      "Premium Crushed Velvet Top",
      "100% Cotton Underside",
      "Hidden Zipper Closure",
      "Includes 2 Matching Shams",
    ],
    specifications: {
      Material: "Velvet & Cotton Blend",
      "Thread Count": "400 TC",
      "Set Includes": "1 Duvet Cover, 2 Pillow Shams",
    },
  },
  {
    name: "Luxury Cotton Sheets",
    code: "sheet-luxury",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/luxury-cotton-sheet",
    price: 85.0,
    image: "/images/bedding/new/sheet_01.png",
    slug: "luxury-cotton-sheet",
    description: "Breathable, 100% cotton sheets for a cool, crisp, and comfortable sleep.",
    longDescription:
      "Our Luxury Cotton Sheets are designed for those who value a good night's sleep above all. Made from long-staple cotton, these sheets get softer with every wash.",
    features: [
      "100% Long-Staple Cotton",
      "Cool Percale Weave",
      "Deep Pockets",
      "Fade-Resistant Colors",
    ],
    specifications: {
      Material: "100% Cotton",
      "Thread Count": "300 TC",
      Weave: "Percale",
    },
  },
  {
    name: "Cloud Soft Pillow",
    code: "pillow-cloud",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/cloud-soft-pillow",
    price: 45.0,
    image: "/images/bedding/new/pillow_01.jpg",
    slug: "cloud-soft-pillow",
    description:
      "Drift away on our Cloud Soft Pillow. Hypoallergenic fill mimicking the feel of down.",
    longDescription:
      "The Cloud Soft Pillow is engineered to provide the perfect balance of fluffiness and support. Filled with a premium down alternative, it supports your neck and head while feeling incredibly soft.",
    features: [
      "Down-Alternative Microfiber Fill",
      "Hypoallergenic",
      "Cotton Cover",
      "Machine Washable",
    ],
    specifications: {
      "Fill Material": "Microfiber",
      "Cover Material": "100% Cotton",
      Firmness: "Medium-Soft",
    },
  },
  {
    name: "Cozy Crib Bedding",
    code: "crib-cozy",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/cozy-crib-bedding",
    price: 65.0,
    image: "/images/bedding/kids_bedding_set.png",
    slug: "cozy-crib-bedding",
    description: "Soft, safe, and adorable bedding for your little one's nursery.",
    longDescription:
      "Create a dreamy nursery with our Cozy Crib Bedding set. Made from organic cotton, it is free from harmful chemicals and incredibly soft against your baby's delicate skin.",
    features: [
      "100% Organic Cotton",
      "Breathable & Lightweight",
      "Fitted Sheet with Elastic",
      "Cute Animal Prints",
    ],
    specifications: {
      Material: "100% Organic Cotton",
      "Set Includes": "1 Fitted Crib Sheet, 1 Baby Blanket",
      Certifications: "GOTS Certified",
    },
  },
  {
    name: "Elegant Bridal Set",
    code: "bridal-set-1",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/elegant-bridal-bedding",
    price: 250.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "elegant-bridal-bedding",
    description: "A complete luxury bedding ensemble for the newlyweds.",
    longDescription:
      "Celebrate new beginnings with our Elegant Bridal Set. This 8-piece ensemble features intricate embroidery, fancy lace trimmings, and lustrous fabrics that add a touch of romance and grandeur.",
    features: [
      "Complete 8-Piece Set",
      "Luxury Jacquard Fabric",
      "Embroidered Details",
      "Includes Decorative Cushions",
    ],
    specifications: {
      Material: "Jacquard & Cotton",
      "Set Includes": "1 Comforter, 1 Bed Sheet, 2 Pillowcases, 2 Shams, 2 Cushions",
      Style: "Bridal Luxury",
    },
  },
  {
    name: "Velvet Touch Comforter",
    code: "comforter-z2",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/velvet-touch-comforter",
    price: 150.0,
    image: "/images/zebaish2.jpg",
    slug: "velvet-touch-comforter",
    description: "Plush, warm, and stylish. Adds a layer of sophistication.",
    longDescription:
      "Wrap yourself in warmth with the Velvet Touch Comforter. The top side features a lush velvet texture that looks stunning, while the reverse is soft microfiber for comfort.",
    features: [
      "Soft Velvet Texture",
      "Warm Poly-Fill",
      "Box Stitch Design",
      "Rich Jewel Tones",
    ],
    specifications: {
      Material: "Polyester Velvet",
      Fill: "Polyester Fiber",
      "Warmth Rating": "High",
    },
  },
  {
    name: "Sateen Finish Sheet",
    code: "sheet-z3",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/sateen-finish-sheet",
    price: 95.0,
    image: "/images/zebaish3.jpg",
    slug: "sateen-finish-sheet",
    description: "Silky smooth sateen sheets that offer a lustrous sheen.",
    longDescription:
      "Experience the silk-like feel of our Sateen Finish Sheets. The sateen weave allows more yarn surface on the face of the fabric, producing a soft hand and a lustrous sheen.",
    features: [
      "Silky Sateen Weave",
      "Wrinkle-Resistant",
      "Luminous Sheen",
      "Soft & Drapey",
    ],
    specifications: {
      Material: "Cotton Blend",
      "Thread Count": "600 TC Equivalent",
      Weave: "Sateen",
    },
  },
  {
    name: "Premium Duvet Set",
    code: "duvet-z4",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/premium-duvet-set",
    price: 180.0,
    image: "/images/zebaish4.jpg",
    slug: "premium-duvet-set",
    description: "Modern designs meets classic comfort.",
    longDescription:
      "Refresh your bedroom instantly with our Premium Duvet Set. Featuring modern geometric or floral prints on high-quality fabric that stands the test of time.",
    features: [
      "Modern Prints",
      "Soft Microfiber Fabric",
      "Button Closure",
      "Corner Ties",
    ],
    specifications: {
      Material: "Brushed Microfiber",
      Pattern: "Various Prints",
      Closure: "Button",
    },
  },
  {
    name: "Premium Sofa Cover",
    code: "sofa-cover-premium",
    category: "Sofa Covers",
    brand: "Zebaish",
    link: "/products/sofa-cover-premium",
    price: 95.0,
    image: "/images/bedding/new/sofa_cover.png",
    slug: "sofa-cover-premium",
    description: "Transform your living room with our elegant, durable sofa covers in various designs.",
    longDescription:
      "Refresh your living space with our Premium Sofa Cover. Made from high-quality stretch fabric, it fits snugly on most standard sofas while protecting them from spills, stains, and wear.",
    features: [
      "Stretchable Fabric",
      "Easy to Install",
      "Washable & Durable",
      "Multiple Color Options",
    ],
    specifications: {
      Material: "Polyester Spandex Blend",
      "Fit Type": "Universal Stretch",
      Care: "Machine Washable",
    },
  },
  {
    name: "Luxury Velvet Sofa Cover",
    code: "sofa-cover-velvet",
    category: "Sofa Covers",
    brand: "Zebaish",
    link: "/products/sofa-cover-velvet",
    price: 125.0,
    image: "/images/bedding/new/sofa_cover.png",
    slug: "sofa-cover-velvet",
    description: "Luxurious velvet sofa cover that adds elegance and protects your furniture.",
    longDescription:
      "Elevate your living room décor with our Luxury Velvet Sofa Cover. The plush velvet texture provides a sophisticated look while the stretch fabric ensures a perfect fit.",
    features: [
      "Premium Velvet Material",
      "Non-Slip Bottom",
      "Stain Resistant",
      "Available in Rich Colors",
    ],
    specifications: {
      Material: "Velvet & Spandex",
      "Fit Type": "Elastic Stretch",
      Sizes: "1-4 Seater Options",
    },
  },
  {
    name: "Jacquard Sofa Cover",
    code: "sofa-cover-jacquard",
    category: "Sofa Covers",
    brand: "Zebaish",
    link: "/products/sofa-cover-jacquard",
    price: 110.0,
    image: "/images/bedding/new/sofa_cover.png",
    slug: "sofa-cover-jacquard",
    description: "Elegant jacquard pattern sofa cover with exquisite detailing.",
    longDescription:
      "Add a touch of sophistication with our Jacquard Sofa Cover. The intricate woven patterns create a luxurious look that complements any interior design style.",
    features: [
      "Jacquard Woven Pattern",
      "Thick & Durable Fabric",
      "Anti-Slip Design",
      "Classic Patterns",
    ],
    specifications: {
      Material: "Jacquard Fabric",
      Pattern: "Various Classic Designs",
      "Fit Type": "Form-Fitting",
    },
  },
  // Additional Bed Sheets
  {
    name: "Egyptian Cotton Sheets",
    code: "sheet-egyptian-800",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/egyptian-cotton-sheets-800",
    price: 135.0,
    image: "/images/bedding/new/sheet_egyptian.png",
    slug: "egyptian-cotton-sheets-800",
    description: "Ultra-premium 800 thread count Egyptian cotton sheets for ultimate luxury.",
    longDescription:
      "Experience the pinnacle of luxury with our Egyptian Cotton Sheets. Featuring an incredible 800 thread count, these sheets offer unparalleled softness and durability.",
    features: [
      "100% Egyptian Cotton",
      "800 Thread Count",
      "Deep Pocket Design",
      "Exceptionally Soft",
    ],
    specifications: {
      Material: "100% Egyptian Cotton",
      "Thread Count": "800 TC",
      "Pocket Depth": "18 inches",
    },
  },
  {
    name: "Bamboo Cooling Sheets",
    code: "sheet-bamboo-cool",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/bamboo-cooling-sheets",
    price: 110.0,
    image: "/images/bedding/new/sheet_bamboo.png",
    slug: "bamboo-cooling-sheets",
    description: "Naturally cooling bamboo sheets that regulate temperature for better sleep.",
    longDescription:
      "Stay cool all night with our Bamboo Cooling Sheets. Made from sustainable bamboo fibers, these sheets are naturally temperature-regulating and incredibly soft.",
    features: [
      "Bamboo Rayon Fabric",
      "Temperature Regulating",
      "Moisture Wicking",
      "Eco-Friendly",
    ],
    specifications: {
      Material: "Bamboo Rayon",
      "Thread Count": "400 TC Equivalent",
      Care: "Machine Washable",
    },
  },
  {
    name: "Microfiber Soft Sheets",
    code: "sheet-microfiber-soft",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/microfiber-soft-sheets",
    price: 65.0,
    image: "/images/bedding/new/sheet_microfiber.png",
    slug: "microfiber-soft-sheets",
    description: "Affordable luxury with ultra-soft brushed microfiber sheets.",
    longDescription:
      "Enjoy premium comfort without the premium price. Our Microfiber Soft Sheets are brushed to perfection for a cloud-like sleeping experience.",
    features: [
      "Brushed Microfiber",
      "Wrinkle Resistant",
      "Fade Resistant",
      "Easy Care",
    ],
    specifications: {
      Material: "Brushed Microfiber",
      "GSM Weight": "105 GSM",
      Care: "Machine Washable",
    },
  },
  {
    name: "Linen Rustic Sheets",
    code: "sheet-linen-rustic",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/linen-rustic-sheets",
    price: 145.0,
    image: "/images/zebaish4.jpg",
    slug: "linen-rustic-sheets",
    description: "Natural European linen sheets with a relaxed, rustic charm.",
    longDescription:
      "Embrace the natural beauty of linen with our Rustic Linen Sheets. These sheets get softer with every wash and offer excellent breathability.",
    features: [
      "100% European Linen",
      "Breathable \u0026 Natural",
      "Gets Softer Over Time",
      "Eco-Friendly",
    ],
    specifications: {
      Material: "100% Linen",
      Weight: "Stone Washed",
      Origin: "European Flax",
    },
  },
  {
    name: "Silk Luxury Sheets",
    code: "sheet-silk-luxury",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/silk-luxury-sheets",
    price: 285.0,
    image: "/images/bedding/new/hero_new_1.png",
    slug: "silk-luxury-sheets",
    description: "Pure mulberry silk sheets for the ultimate in luxury and skin care.",
    longDescription:
      "Indulge in pure silk luxury. Our Mulberry Silk Sheets are gentle on skin and hair, naturally hypoallergenic, and temperature regulating.",
    features: [
      "100% Mulberry Silk",
      "19 Momme Weight",
      "Hypoallergenic",
      "Anti-Aging Benefits",
    ],
    specifications: {
      Material: "100% Mulberry Silk",
      Weight: "19 Momme",
      Grade: "6A Grade",
    },
  },
  {
    name: "Jersey Knit Sheets",
    code: "sheet-jersey-knit",
    category: "Bed Sheets",
    brand: "Zebaish",
    link: "/products/jersey-knit-sheets",
    price: 75.0,
    image: "/images/zebaish2.jpg",
    slug: "jersey-knit-sheets",
    description: "Soft and stretchy jersey knit sheets that feel like your favorite t-shirt.",
    longDescription:
      "Experience the comfort of your favorite t-shirt in bed. Our Jersey Knit Sheets are soft, stretchy, and perfect for cozy nights.",
    features: [
      "Cotton Jersey Knit",
      "Stretchy \u0026 Soft",
      "Casual Comfort",
      "Easy Care",
    ],
    specifications: {
      Material: "Cotton Jersey",
      Weight: "150 GSM",
      Stretch: "4-Way Stretch",
    },
  },
  // Additional Duvet Sets
  {
    name: "Geometric Pattern Duvet",
    code: "duvet-geometric",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/geometric-pattern-duvet",
    price: 165.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "geometric-pattern-duvet",
    description: "Modern geometric patterns bring contemporary style to your bedroom.",
    longDescription:
      "Transform your bedroom with bold geometric designs. This duvet set features clean lines and modern patterns that complement any contemporary décor.",
    features: [
      "Modern Geometric Design",
      "Microfiber Fabric",
      "Zipper Closure",
      "Matching Shams Included",
    ],
    specifications: {
      Material: "Microfiber",
      Pattern: "Geometric",
      "Set Includes": "1 Duvet Cover, 2 Shams",
    },
  },
  {
    name: "Floral Romance Duvet",
    code: "duvet-floral",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/floral-romance-duvet",
    price: 155.0,
    image: "/images/zebaish2.jpg",
    slug: "floral-romance-duvet",
    description: "Romantic floral prints create a soft, feminine bedroom atmosphere.",
    longDescription:
      "Bring garden-inspired beauty to your bedroom. Our Floral Romance Duvet features delicate blooms and soft colors for a serene sleeping space.",
    features: [
      "Floral Print Design",
      "Soft Cotton Blend",
      "Reversible",
      "Easy Care",
    ],
    specifications: {
      Material: "Cotton Blend",
      Pattern: "Floral",
      Closure: "Button",
    },
  },
  {
    name: "Modern Minimalist Duvet",
    code: "duvet-minimalist",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/modern-minimalist-duvet",
    price: 140.0,
    image: "/images/zebaish3.jpg",
    slug: "modern-minimalist-duvet",
    description: "Clean, simple design for the modern minimalist bedroom.",
    longDescription:
      "Less is more with our Modern Minimalist Duvet. Featuring solid colors and clean lines, it's perfect for contemporary spaces.",
    features: [
      "Solid Color Design",
      "Premium Cotton",
      "Minimalist Style",
      "Hidden Closures",
    ],
    specifications: {
      Material: "100% Cotton",
      Style: "Minimalist",
      Colors: "Multiple Options",
    },
  },
  {
    name: "Boho Chic Duvet",
    code: "duvet-boho",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/boho-chic-duvet",
    price: 175.0,
    image: "/images/bedding/new/hero_new_2.png",
    slug: "boho-chic-duvet",
    description: "Bohemian-inspired patterns and textures for a free-spirited bedroom.",
    longDescription:
      "Express your free spirit with our Boho Chic Duvet. Featuring eclectic patterns and rich textures inspired by global textiles.",
    features: [
      "Bohemian Patterns",
      "Textured Fabric",
      "Tassel Details",
      "Unique Design",
    ],
    specifications: {
      Material: "Cotton \u0026 Polyester",
      Style: "Bohemian",
      Details: "Decorative Tassels",
    },
  },
  {
    name: "Scandinavian Style Duvet",
    code: "duvet-scandi",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/scandinavian-style-duvet",
    price: 160.0,
    image: "/images/bedding/new/duvet_01.png",
    slug: "scandinavian-style-duvet",
    description: "Nordic-inspired simplicity with natural colors and clean design.",
    longDescription:
      "Embrace Scandinavian design principles with our Nordic-inspired duvet. Features natural tones and simple, functional beauty.",
    features: [
      "Nordic Design",
      "Natural Colors",
      "Sustainable Materials",
      "Simple Elegance",
    ],
    specifications: {
      Material: "Organic Cotton",
      Style: "Scandinavian",
      Colors: "Neutral Tones",
    },
  },
  {
    name: "Tropical Paradise Duvet",
    code: "duvet-tropical",
    category: "Duvet Sets",
    brand: "Zebaish",
    link: "/products/tropical-paradise-duvet",
    price: 170.0,
    image: "/images/zebaish4.jpg",
    slug: "tropical-paradise-duvet",
    description: "Vibrant tropical prints bring vacation vibes to your bedroom.",
    longDescription:
      "Escape to paradise every night with our Tropical Paradise Duvet. Bold prints featuring palm leaves and tropical flowers create a resort-like atmosphere.",
    features: [
      "Tropical Print",
      "Vibrant Colors",
      "Vacation Vibes",
      "Lightweight",
    ],
    specifications: {
      Material: "Cotton Blend",
      Pattern: "Tropical",
      Weight: "Lightweight",
    },
  },
  // Additional Comforters
  {
    name: "All-Season Down Alternative",
    code: "comforter-all-season",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/all-season-down-alternative",
    price: 135.0,
    image: "/images/zebaish3.jpg",
    slug: "all-season-down-alternative",
    description: "Perfect year-round comfort with our versatile all-season comforter.",
    longDescription:
      "One comforter for all seasons. Our All-Season Down Alternative provides just the right warmth for spring, summer, fall, and winter.",
    features: [
      "Medium Weight",
      "Down Alternative Fill",
      "Hypoallergenic",
      "All-Season Comfort",
    ],
    specifications: {
      Fill: "Down Alternative",
      Weight: "Medium",
      "Warmth Level": "3/5",
    },
  },
  {
    name: "Winter Warmth Comforter",
    code: "comforter-winter",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/winter-warmth-comforter",
    price: 165.0,
    image: "/images/bedding/new/hero_new_1.png",
    slug: "winter-warmth-comforter",
    description: "Extra-warm comforter designed for cold winter nights.",
    longDescription:
      "Stay cozy all winter long. Our Winter Warmth Comforter features extra fill for maximum warmth on the coldest nights.",
    features: [
      "Extra Warm",
      "Heavy Fill",
      "Box Stitch Construction",
      "Winter Weight",
    ],
    specifications: {
      Fill: "Premium Poly-Fill",
      Weight: "Heavy",
      "Warmth Level": "5/5",
    },
  },
  {
    name: "Lightweight Summer Comforter",
    code: "comforter-summer",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/lightweight-summer-comforter",
    price: 95.0,
    image: "/images/zebaish4.jpg",
    slug: "lightweight-summer-comforter",
    description: "Breathable, lightweight comfort perfect for warm weather.",
    longDescription:
      "Beat the summer heat with our Lightweight Summer Comforter. Designed to provide just enough coverage without overheating.",
    features: [
      "Lightweight Fill",
      "Breathable Fabric",
      "Cool Comfort",
      "Summer Weight",
    ],
    specifications: {
      Fill: "Thin Poly-Fill",
      Weight: "Light",
      "Warmth Level": "1/5",
    },
  },
  {
    name: "Quilted Patchwork Comforter",
    code: "comforter-quilt",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/quilted-patchwork-comforter",
    price: 145.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "quilted-patchwork-comforter",
    description: "Classic quilted design with charming patchwork patterns.",
    longDescription:
      "Add vintage charm to your bedroom with our Quilted Patchwork Comforter. Features traditional quilting techniques and beautiful patterns.",
    features: [
      "Quilted Design",
      "Patchwork Pattern",
      "Classic Style",
      "Durable Construction",
    ],
    specifications: {
      Style: "Quilted Patchwork",
      Construction: "Box Stitch",
      Pattern: "Various",
    },
  },
  {
    name: "Reversible Two-Tone Comforter",
    code: "comforter-reversible",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/reversible-two-tone-comforter",
    price: 125.0,
    image: "/images/zebaish2.jpg",
    slug: "reversible-two-tone-comforter",
    description: "Two looks in one with our reversible two-tone design.",
    longDescription:
      "Change your bedroom's look in seconds. Our Reversible Comforter offers two complementary colors for versatile styling.",
    features: [
      "Reversible Design",
      "Two Color Options",
      "Versatile Styling",
      "Easy to Flip",
    ],
    specifications: {
      Design: "Reversible",
      Colors: "Dual-Tone",
      Material: "Microfiber",
    },
  },
  {
    name: "Microfiber Plush Comforter",
    code: "comforter-plush",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/microfiber-plush-comforter",
    price: 110.0,
    image: "/images/zebaish3.jpg",
    slug: "microfiber-plush-comforter",
    description: "Ultra-plush microfiber for the softest sleeping experience.",
    longDescription:
      "Sink into luxury with our Microfiber Plush Comforter. The ultra-soft fabric feels like a warm hug every night.",
    features: [
      "Ultra-Soft Microfiber",
      "Plush Texture",
      "Warm \u0026 Cozy",
      "Machine Washable",
    ],
    specifications: {
      Material: "Plush Microfiber",
      Texture: "Ultra-Soft",
      Care: "Machine Washable",
    },
  },
  {
    name: "Cooling Gel Comforter",
    code: "comforter-cooling",
    category: "Comforters",
    brand: "Zebaish",
    link: "/products/cooling-gel-comforter",
    price: 175.0,
    image: "/images/zebaish4.jpg",
    slug: "cooling-gel-comforter",
    description: "Advanced cooling technology for hot sleepers.",
    longDescription:
      "Stay cool all night with our Cooling Gel Comforter. Infused with cooling gel particles that regulate temperature for better sleep.",
    features: [
      "Cooling Gel Technology",
      "Temperature Regulating",
      "Moisture Wicking",
      "Perfect for Hot Sleepers",
    ],
    specifications: {
      Technology: "Cooling Gel",
      Material: "Performance Fabric",
      "Cooling Level": "Maximum",
    },
  },
  // Additional Pillows
  {
    name: "Memory Foam Contour Pillow",
    code: "pillow-memory-foam",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/memory-foam-contour-pillow",
    price: 65.0,
    image: "/images/bedding/new/pillow_01.jpg",
    slug: "memory-foam-contour-pillow",
    description: "Ergonomic contour design provides perfect neck support.",
    longDescription:
      "Wake up pain-free with our Memory Foam Contour Pillow. The ergonomic design aligns your spine and reduces neck pain.",
    features: [
      "Memory Foam",
      "Contour Design",
      "Neck Support",
      "Hypoallergenic",
    ],
    specifications: {
      Fill: "Memory Foam",
      Shape: "Contour",
      Firmness: "Medium-Firm",
    },
  },
  {
    name: "Cooling Gel Pillow",
    code: "pillow-cooling-gel",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/cooling-gel-pillow",
    price: 55.0,
    image: "/images/bedding/new/hero_new_2.png",
    slug: "cooling-gel-pillow",
    description: "Gel-infused memory foam keeps you cool all night.",
    longDescription:
      "Stay cool and comfortable with our Cooling Gel Pillow. Gel infusion prevents heat retention for refreshing sleep.",
    features: [
      "Gel-Infused Foam",
      "Cooling Technology",
      "Heat Dissipation",
      "Breathable Cover",
    ],
    specifications: {
      Fill: "Gel Memory Foam",
      Technology: "Cooling Gel",
      "Temperature Control": "Advanced",
    },
  },
  {
    name: "Feather Down Pillow",
    code: "pillow-feather",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/feather-down-pillow",
    price: 85.0,
    image: "/images/zebaish3.jpg",
    slug: "feather-down-pillow",
    description: "Luxurious blend of feathers and down for cloud-like softness.",
    longDescription:
      "Experience hotel luxury at home. Our Feather Down Pillow combines the support of feathers with the softness of down.",
    features: [
      "Feather \u0026 Down Fill",
      "Luxury Comfort",
      "Adjustable Loft",
      "Cotton Shell",
    ],
    specifications: {
      Fill: "75% Feather, 25% Down",
      Shell: "100% Cotton",
      "Fill Power": "600+ ",
    },
  },
  {
    name: "Bamboo Charcoal Pillow",
    code: "pillow-bamboo",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/bamboo-charcoal-pillow",
    price: 60.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "bamboo-charcoal-pillow",
    description: "Natural bamboo charcoal eliminates odors and regulates temperature.",
    longDescription:
      "Harness the power of bamboo charcoal. This pillow naturally purifies air, eliminates odors, and keeps you cool.",
    features: [
      "Bamboo Charcoal Infused",
      "Odor Eliminating",
      "Temperature Regulating",
      "Eco-Friendly",
    ],
    specifications: {
      Fill: "Bamboo Charcoal Memory Foam",
      Benefits: "Odor Control, Cooling",
      Material: "Natural Bamboo",
    },
  },
  {
    name: "Latex Support Pillow",
    code: "pillow-latex",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/latex-support-pillow",
    price: 95.0,
    image: "/images/zebaish2.jpg",
    slug: "latex-support-pillow",
    description: "Natural latex provides responsive support and durability.",
    longDescription:
      "Get superior support with our Latex Support Pillow. Natural latex is responsive, supportive, and naturally resistant to dust mites.",
    features: [
      "100% Natural Latex",
      "Responsive Support",
      "Durable",
      "Dust Mite Resistant",
    ],
    specifications: {
      Fill: "Natural Latex",
      Support: "Firm",
      Durability: "10+ Years",
    },
  },
  {
    name: "Body Pillow",
    code: "pillow-body",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/body-pillow",
    price: 70.0,
    image: "/images/zebaish4.jpg",
    slug: "body-pillow",
    description: "Full-length body pillow for side sleepers and pregnancy support.",
    longDescription:
      "Perfect for side sleepers and expectant mothers. Our Body Pillow provides full-body support for ultimate comfort.",
    features: [
      "Full Length Design",
      "Side Sleeper Support",
      "Pregnancy Friendly",
      "Removable Cover",
    ],
    specifications: {
      Size: "54 inches Long",
      Fill: "Polyester Fiber",
      Use: "Side Sleeping, Pregnancy",
    },
  },
  {
    name: "Travel Mini Pillow",
    code: "pillow-travel",
    category: "Pillows",
    brand: "Zebaish",
    link: "/products/travel-mini-pillow",
    price: 35.0,
    image: "/images/bedding/new/pillow_01.jpg",
    slug: "travel-mini-pillow",
    description: "Compact travel pillow for comfort on the go.",
    longDescription:
      "Never compromise on comfort while traveling. Our Travel Mini Pillow is compact, portable, and provides excellent neck support.",
    features: [
      "Compact Size",
      "Portable",
      "Neck Support",
      "Carry Bag Included",
    ],
    specifications: {
      Size: "12 x 16 inches",
      Weight: "Lightweight",
      Portability: "Travel-Friendly",
    },
  },
  // Additional Kids Bedding
  {
    name: "Dinosaur Adventure Set",
    code: "kids-dinosaur",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/dinosaur-adventure-set",
    price: 70.0,
    image: "/images/bedding/kids_bedding_set.png",
    slug: "dinosaur-adventure-set",
    description: "Roar into bedtime with fun dinosaur prints and vibrant colors.",
    longDescription:
      "Make bedtime an adventure with our Dinosaur Adventure Set. Features friendly dinos and lush prehistoric landscapes.",
    features: [
      "Dinosaur Print",
      "100% Cotton",
      "Safe for Kids",
      "Easy Care",
    ],
    specifications: {
      Material: "100% Cotton",
      Theme: "Dinosaurs",
      "Age Range": "2-10 years",
    },
  },
  {
    name: "Princess Dreams Set",
    code: "kids-princess",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/princess-dreams-set",
    price: 75.0,
    image: "/images/bedding/new/hero_new_2.png",
    slug: "princess-dreams-set",
    description: "Royal pink and purple hues with princess castles and crowns.",
    longDescription:
      "Every little princess deserves a royal bedroom. Our Princess Dreams Set features castles, crowns, and magical details.",
    features: [
      "Princess Theme",
      "Soft Pink Colors",
      "Glitter Accents",
      "Hypoallergenic",
    ],
    specifications: {
      Material: "Organic Cotton",
      Colors: "Pink \u0026 Purple",
      Details: "Sparkle Details",
    },
  },
  {
    name: "Space Explorer Set",
    code: "kids-space",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/space-explorer-set",
    price: 72.0,
    image: "/images/zebaish3.jpg",
    slug: "space-explorer-set",
    description: "Blast off to dreamland with rockets, planets, and stars.",
    longDescription:
      "Explore the universe every night. Our Space Explorer Set features rockets, planets, and twinkling stars for budding astronauts.",
    features: [
      "Space Theme",
      "Glow-in-Dark Stars",
      "Educational",
      "Soft Cotton",
    ],
    specifications: {
      Material: "Cotton Blend",
      Theme: "Outer Space",
      Special: "Glow in Dark Elements",
    },
  },
  {
    name: "Jungle Safari Set",
    code: "kids-jungle",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/jungle-safari-set",
    price: 68.0,
    image: "/images/zebaish4.jpg",
    slug: "jungle-safari-set",
    description: "Wild jungle animals and lush greenery create an adventure zone.",
    longDescription:
      "Go on a safari every night. Our Jungle Safari Set features lions, elephants, and monkeys in a vibrant jungle setting.",
    features: [
      "Jungle Animal Print",
      "Vibrant Colors",
      "Educational Elements",
      "Safe Dyes",
    ],
    specifications: {
      Material: "100% Cotton",
      Theme: "Jungle Safari",
      Colors: "Earth Tones",
    },
  },
  {
    name: "Unicorn Magic Set",
    code: "kids-unicorn",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/unicorn-magic-set",
    price: 78.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "unicorn-magic-set",
    description: "Magical unicorns, rainbows, and sparkles for a dreamy bedroom.",
    longDescription:
      "Believe in magic with our Unicorn Magic Set. Features beautiful unicorns, rainbows, and magical sparkles.",
    features: [
      "Unicorn Design",
      "Rainbow Colors",
      "Sparkle Details",
      "Ultra Soft",
    ],
    specifications: {
      Material: "Organic Cotton",
      Theme: "Unicorns \u0026 Rainbows",
      Special: "Holographic Accents",
    },
  },
  {
    name: "Race Car Theme Set",
    code: "kids-racecar",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/race-car-theme-set",
    price: 69.0,
    image: "/images/zebaish2.jpg",
    slug: "race-car-theme-set",
    description: "Speed into bedtime with racing cars and checkered flags.",
    longDescription:
      "Rev up bedtime excitement. Our Race Car Theme Set features colorful racing cars and checkered flag patterns.",
    features: [
      "Race Car Print",
      "Bold Colors",
      "Action Theme",
      "Durable Fabric",
    ],
    specifications: {
      Material: "Cotton Blend",
      Theme: "Racing Cars",
      Colors: "Red, Blue, Black",
    },
  },
  {
    name: "Ocean Friends Set",
    code: "kids-ocean",
    category: "Kids Bedding",
    brand: "Zebaish",
    link: "/products/ocean-friends-set",
    price: 71.0,
    image: "/images/bedding/new/hero_new_1.png",
    slug: "ocean-friends-set",
    description: "Dive into sleep with friendly sea creatures and ocean waves.",
    longDescription:
      "Explore the ocean depths with our Ocean Friends Set. Features dolphins, turtles, fish, and coral reef designs.",
    features: [
      "Ocean Theme",
      "Sea Creature Prints",
      "Calming Blues",
      "Soft \u0026 Safe",
    ],
    specifications: {
      Material: "100% Cotton",
      Theme: "Ocean Life",
      Colors: "Blue \u0026 Aqua",
    },
  },
  // Additional Bridal Bedding
  {
    name: "Rose Gold Romance Set",
    code: "bridal-rosegold",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/rose-gold-romance-set",
    price: 280.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "rose-gold-romance-set",
    description: "Stunning rose gold accents add modern elegance to bridal luxury.",
    longDescription:
      "Celebrate your special day with our Rose Gold Romance Set. Featuring metallic rose gold embroidery and delicate lace details.",
    features: [
      "Rose Gold Embroidery",
      "Luxury Satin",
      "Complete 8-Piece Set",
      "Hand-Stitched Details",
    ],
    specifications: {
      Material: "Satin \u0026 Cotton",
      Color: "Rose Gold \u0026 Ivory",
      "Set Includes": "Complete 8-Piece",
    },
  },
  {
    name: "Pearl White Elegance Set",
    code: "bridal-pearl",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/pearl-white-elegance-set",
    price: 295.0,
    image: "/images/zebaish3.jpg",
    slug: "pearl-white-elegance-set",
    description: "Pure white with pearl embellishments for timeless elegance.",
    longDescription:
      "Classic bridal beauty with our Pearl White Elegance Set. Features genuine pearl-like beading and intricate lacework.",
    features: [
      "Pearl Embellishments",
      "Pure White",
      "Luxury Jacquard",
      "Premium Quality",
    ],
    specifications: {
      Material: "Jacquard \u0026 Silk",
      Color: "Pearl White",
      Details: "Pearl Beading",
    },
  },
  {
    name: "Champagne Luxury Set",
    code: "bridal-champagne",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/champagne-luxury-set",
    price: 265.0,
    image: "/images/zebaish4.jpg",
    slug: "champagne-luxury-set",
    description: "Soft champagne hues create a warm, romantic atmosphere.",
    longDescription:
      "Toast to new beginnings with our Champagne Luxury Set. Warm champagne tones with gold threading create ultimate romance.",
    features: [
      "Champagne Color",
      "Gold Threading",
      "Silk Touch Fabric",
      "Luxury Design",
    ],
    specifications: {
      Material: "Silk Blend",
      Color: "Champagne",
      "Thread Work": "Gold",
    },
  },
  {
    name: "Ivory Dreams Set",
    code: "bridal-ivory",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/ivory-dreams-set",
    price: 270.0,
    image: "/images/bedding/new/hero_new_1.png",
    slug: "ivory-dreams-set",
    description: "Soft ivory with delicate floral embroidery for classic beauty.",
    longDescription:
      "Timeless elegance with our Ivory Dreams Set. Features hand-embroidered floral patterns and scalloped lace edges.",
    features: [
      "Ivory Tone",
      "Floral Embroidery",
      "Scalloped Lace",
      "Romantic Design",
    ],
    specifications: {
      Material: "Cotton \u0026 Lace",
      Color: "Ivory",
      Style: "Classic Bridal",
    },
  },
  {
    name: "Blush Pink Deluxe Set",
    code: "bridal-blush",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/blush-pink-deluxe-set",
    price: 275.0,
    image: "/images/bedding/new/hero_new_2.png",
    slug: "blush-pink-deluxe-set",
    description: "Romantic blush pink with rose appliqués and ribbon details.",
    longDescription:
      "Soft romance in blush pink. Our Deluxe Set features 3D rose appliqués and satin ribbon details for a fairy tale bedroom.",
    features: [
      "Blush Pink Color",
      "3D Rose Appliqués",
      "Satin Ribbons",
      "Premium Fabric",
    ],
    specifications: {
      Material: "Satin \u0026 Cotton",
      Color: "Blush Pink",
      Details: "3D Flowers",
    },
  },
  {
    name: "Classic White Bridal Set",
    code: "bridal-classic",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/classic-white-bridal-set",
    price: 260.0,
    image: "/images/zebaish1 (1).jpg",
    slug: "classic-white-bridal-set",
    description: "Traditional pure white with vintage lace for timeless style.",
    longDescription:
      "Honor tradition with our Classic White Bridal Set. Pure white cotton with vintage-inspired lace and eyelet details.",
    features: [
      "Pure White",
      "Vintage Lace",
      "Eyelet Details",
      "Traditional Style",
    ],
    specifications: {
      Material: "100% Cotton",
      Color: "Pure White",
      Style: "Traditional Bridal",
    },
  },
  {
    name: "Gold Embroidered Royal Set",
    code: "bridal-gold-royal",
    category: "Bridal Bedding",
    brand: "Zebaish",
    link: "/products/gold-embroidered-royal-set",
    price: 320.0,
    image: "/images/zebaish2.jpg",
    slug: "gold-embroidered-royal-set",
    description: "Opulent gold embroidery on silk for the ultimate royal wedding.",
    longDescription:
      "Live like royalty with our Gold Embroidered Royal Set. Features intricate gold thread embroidery on pure silk.",
    features: [
      "Gold Embroidery",
      "Pure Silk",
      "Royal Design",
      "Hand-Crafted",
    ],
    specifications: {
      Material: "100% Silk",
      Embroidery: "24K Gold Thread",
      Style: "Royal Luxury",
    },
  },
];

export const heroSlides = [
  {
    title: "Luxury Bedding Collection",
    description: "Experience the comfort of royalty with our premium cotton and velvet bedding sets.",
    cta: "Home Collection",
    link: "/products",
    image: "/images/bedding/new/hero_new_1.png",
  },
  {
    title: "Bridal Bedroom Essentials",
    description: "Transform your special space with our exquisite bridal sets, designed for elegance and romance.",
    cta: "View Bridal Sets",
    link: "/products",
    image: "/images/zebaish1 (1).jpg",
  },
  {
    title: "Premium Home Textiles",
    description: "From soft duvets to crisp sheets, find everything you need for a perfect night's sleep.",
    cta: "Explore More",
    link: "/products",
    image: "/images/bedding/new/hero_new_2.png",
  },
];

// Helper functions (kept for backward compatibility if needed, but updated to use the array)
export function getProductPrice(code: string): number {
  const product = allCollections.find((p) => p.code === code);
  return product ? product.price : 0;
}

export function getProductImage(code: string): string {
  const product = allCollections.find((p) => p.code === code);
  return product ? product.image : "";
}

export function getProductSlug(code: string): string {
  const product = allCollections.find((p) => p.code === code);
  return product ? product.slug : "";
}
